In [1]:
import random
from functools import reduce
import chess
import numpy as np
import chess_game as cg

In [2]:
a = cg.Chess()
src = a.possible_sources(True)
dest = a.possible_destinations(True)

In [14]:
temp = iter(a.board.legal_moves)
a.make_move(next(temp))
a

[[-4 -2 -3 -5 -6 -3 -2 -4]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 1  1  1  1  1  1  1  1]
 [ 4  2  3  5  6  3  2  4]]
True

In [4]:
%%time
a = [i for i in range(10000000)]
for i in a:
    i

Wall time: 2.45 s


In [3]:
%%time
a = {i for i in range(10000000)}
for i in a:
    i

Wall time: 2.69 s
